kind: ConfigMap
apiVersion: v1
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: build-config
  namespace: go-demo-3-build
data:
  build-config.properties: |
    project=go-demo-3
    image=nhatsangvn/go-demo-3
    domain=61.28.237.69.nip.io
    prod-addr=go-demo-3.61.28.237.69.nip.io
    cmAddr=cm.61.28.237.69.nip.io
    chartVer=0.0.1

